import Head from "next/head";
import Image from "next/image";
import Dashboard from "../src/components/Dashboard/Dashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Svashta - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div>
        <Dashboard />
      </div>
    </>
  );
}
